// <auto-generated />
namespace DishLish.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rmvdalllatsandlongs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rmvdalllatsandlongs));
        
        string IMigrationMetadata.Id
        {
            get { return "201610160356315_rmv'd all lats and longs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
